<?php

function mymodule_menu() {
    $items['path-to-ajax/%/%'] = array(
        'access arguements' =>array('access content'),
        'page callback' => 'mymodule_ajax_callback',
        'page arguements' => array(1,2),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function mymodule_ajax_callback($js, $node_id) {
    $node = node_load($node_id);

    if ($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }
}
